#use_frameworks!

platform :ios, '9.0'

target 'ZFNetWorkTool_Example' do
  pod 'ZFNetWorkTool', :path => '../'
  
  pod 'AFNetworking', ‘3.1.0’
  pod ‘MBProgressHUD’, ‘1.0.0’
  pod ‘MJExtension’, ‘3.0.13’

#  target 'ZFNetWorkTool_Tests' do
#    inherit! :search_paths

    
#  end

end
